# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: '$(date:yyyyMMdd)$(rev:.rr)'
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet pack --configuration $(buildConfiguration) /src/**/*.csproj
  displayName: 'dotnet build $(buildConfiguration)'
- task: UpdateNugetPackageVersionsTask@1
  inputs:
    PackageFolder: '$(Build.ArtifactStagingDirectory)'
    PackageFeatureName: 'pre'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'DotNET DevOps Myget'
    versioningScheme: 'off'

